name = "quest-automation"
main = "index.js"
compatibility_date = "2025-10-04"

[triggers]
crons = ["0 23 * * *", "0 8 * * *", "0 * * * *"]

[[kv_namespaces]]
binding = "QUEST_MASTER_DS"
id = "82a781e39b544f9aa0d971f97f2862fc"

[[kv_namespaces]]
binding = "QUEST_LOG_DS"
id = "fc116965737f4ce594aeee12223e0f72"

[[kv_namespaces]]
binding = "DAILY_TRACKER_DS"
id = "936ffd43f0414a32b723f74592719699"

[observability.logs]
enabled = true
